#!/bin/bash
echo -e "\n login as admin"
curl -s -X POST "http://localhost:8080/api/user/login?username=admin&password=admin"
echo -e "\n change admin password"
curl -s -X PUT "localhost:8080/api/user/change_password/?username=admin&oldPass=admin&newPass=administrator"
echo -e "\n create library hour MONDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=MONDAY&startTime=08:00&endTime=19:00"
echo -e "\n modify library hour MONDAY"
curl -s -X PUT "http://localhost:8080/api/libraryhour/modify_library_hour?currentUserId=admin&dayOfWeek=MONDAY&startTime=07:00&endTime=19:00"
echo -e "\n create library hour TUESDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=TUESDAY&startTime=08:00&endTime=19:00" 
echo -e "\n create library hour WEDNESDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=WEDNESDAY&startTime=08:00&endTime=19:00"
echo -e "\n create library hour THURSDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=THURSDAY&startTime=08:00&endTime=19:00"
echo -e "\n create library hour FRIDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=FRIDAY&startTime=08:00&endTime=19:00"
echo -e "\n create library hour SATURDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=SATURDAY&startTime=08:00&endTime=19:00"
echo -e "\n create library hour SUNDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=SUNDAY&startTime=08:00&endTime=19:00"
echo -e "\n delete library hour SUNDAY"
curl -s -X DELETE "http://localhost:8080/api/libraryhour/remove_library_hour?currentUserId=admin&dayOfWeek=SUNDAY"
echo -e "\n create library hour SUNDAY"
curl -s -X POST "http://localhost:8080/api/libraryhour/add_library_hour?currentUserId=admin&dayOfWeek=SUNDAY&startTime=08:00&endTime=19:00"

echo -e "\n create room"
curl -s -X POST "localhost:8080/api/rooms/create_room/study1?capacity=6&currentUserId=admin"
echo -e "\n update room"
curl -s -X PUT "localhost:8080/api/rooms/update_room/study1?newCapacity=10&currentUserId=admin"
echo -e "\n create book"
curl -s -X POST "localhost:8080/api/items/create_book?currentUserId=admin&itemTitle=book&description=cool&imageURL=no-image&publisher=saagar&author=saagar&genre=horror&publishDate=2001-09-22&isReservable=true"
echo -e "\n create archive"
curl -s -X POST "localhost:8080/api/items/create_archive?currentUserId=admin&itemTitle=archive-for-dummies&description=dumb&imageURL=no-image&genre=dumber&publishDate=2001-09-22&isReservable=true"
echo -e "\n create librarian"
curl -s -X POST "http://localhost:8080/api/librarians/create?currentUserId=admin&firstName=Selena&lastName=Libby&address=1234-rue-Sherbrooke-O&email=selena@librarian.com&username=selener&password=selenerpassword"
echo -e "\n create shift"
curl -s -X POST "http://localhost:8080/api/shift/add_shift/?currentUserId=admin&librarianId=SelenaLibrarian-1&dayOfWeek=WEDNESDAY&startTime=10:00&endTime=15:00"
echo -e "\n modify shift"
curl -s -X PUT "localhost:8080/api/shift/modify_shift?currentUserId=admin&librarianId=SelenaLibrarian-1&dayOfWeek=THURSDAY&startTime=10:00&endTime=15:00&timeSlotId=WEDNESDAYSelenaLibrarian-110:00:0015:00:000"
echo -e "\n delete shift"
curl -s -X DELETE "localhost:8080/api/shift/remove_shift?currentUserId=admin&timeSlotId=WEDNESDAYSelenaLibrarian-110:00:0015:00:000"
echo -e "\n logout admin"
curl -s -X POST "localhost:8080/api/user/logout/admin"
echo -e "\n login librarian"
curl -s -X POST "http://localhost:8080/api/user/login?username=selener&password=selenerpassword"
echo -e "\n change librarian password"
curl -s -X PUT "http://localhost:8080/api/user/change_password?oldPass=selenerpassword&newPass=newselenerpassword&username=selener"
echo -e "\n create patron irl"
curl -s -X POST "localhost:8080/api/patron/create_patron_irl?first=Kevin&last=kevinpassword&isResident=true&address=1234-none-of-ur-business"
echo -e "\n delete patron"
curl -s -X DELETE "localhost:8080/api/patron/delete_patron/KevinPatron-0?currentUserId=SelenaLibrarian-1"
echo -e "\n logout librarian"
curl -s -X POST "localhost:8080/api/user/logout/selener"
echo -e "\n create patron online"
curl -s -X POST "localhost:8080/api/patron/create_patron_online?username=Sergei&password=sergeipassword&first=Sergei&last=password&isResident=true&address=1234-none-of-ur-business&email=business1@none.com"

echo -e "\n login patron"
curl -s -X POST "http://localhost:8080/api/user/login?username=Sergei&password=sergeipassword"
echo -e "\n change patron name"
curl -s -X PUT "localhost:8080/api/user/change_name/?username=Sergei&firstName=Soogy&lastName=SSSS"
echo -e "\n create room booking"
curl -s -X POST "localhost:8080/api/roombookings/add_roombooking/?currentUserId=SergeiPatron-0&idNum=SergeiPatron-0&roomNum=study1&date=2022-11-11&startTime=12:30&endTime=14:30"
echo -e "\n update room booking"
curl -s -X PUT "http://localhost:8080/api/roombookings/update_roombooking?currentUserId=SergeiPatron-0&timeSlotId=RoomBooking-012:30study1&newDate=2022-11-13&newStartTime=11:11&newEndTime=12:00&newRoomNum=study1"
echo -e "\n delete room booking"
curl -s -X DELETE "http://localhost:8080/api/roombookings/delete_roombooking?timeSlotId=RoomBooking-012:30study1&currentUserId=SergeiPatron-0"
echo -e "\n create reservation"
curl -s -X POST "localhost:8080/api/itemReservations/create_reservation/?currentUserId=SergeiPatron-0&idNum=SergeiPatron-0&itemNumber=Book-0book&isCheckedOut=false"
echo -e "\n renew reservation"
curl -s -X PUT "localhost:8080/api/itemReservations/renew/Book-0bookSergeiPatron-00?currentUserId=SergeiPatron-0"
echo -e "\n logout patron"
curl -s -X POST "localhost:8080/api/user/logout/Sergei"
echo -e "\n login as admin again"
curl -s -X POST "http://localhost:8080/api/user/login?username=admin&password=administrator"
echo -e "\n checkout item during reservation"
curl -s -X PUT "localhost:8080/api/itemReservations/checkout_item/Book-0book/byPatron/SergeiPatron-0?currentUserId=admin"
echo -e "\n return item"
curl -s -X PUT "localhost:8080/api/itemReservations/return_item/Book-0book/?currentUserId=admin"
echo -e "\n create archive reservation"
curl -s -X POST "localhost:8080/api/itemReservations/create_reservation/?currentUserId=admin&idNum=SergeiPatron-0&itemNumber=Archive-0archive-for-dummies&isCheckedOut=false"
echo -e "\n cancel reservation"
curl -s -X DELETE "localhost:8080/api/itemReservations/cancel/Archive-0archive-for-dummiesSergeiPatron-01?currentUserId=admin"
echo -e "\n delete book"
curl -s -X DELETE "localhost:8080/api/items/delete/Book-0book?currentUserId=admin"
echo -e "\n delete room"
curl -s -X DELETE "http://localhost:8080/api/rooms/delete_room/study1?currentUserId=admin"
echo -e "\n delete librarian"
curl -s -X DELETE "localhost:8080/api/librarians/delete/SelenaLibrarian-1?currentUserId=admin"

